# Generated by Django 5.0 on 2023-12-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_expense', models.CharField(max_length=255)),
                ('spent_at', models.DateField()),
                ('expense_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
